<?php

/**
 * @file
 * This file contains all install functions
 */

/**
 * Implements hook_install().
 *
 * @see islandora_basic_collection_islandora_required_objects()
 */
function islandora_basic_collection_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_basic_collection');
}

/**
 * Implements hook_uninstall().
 */
function islandora_basic_collection_uninstall() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_basic_collection', 'uninstall');
  $variables = array(
    'islandora_basic_collection_generate_uuid',
    'islandora_basic_collection_page_size',
    'islandora_basic_collection_disable_collection_policy_delete',
    'islandora_basic_collection_default_view',
  );
  array_walk($variables, 'variable_del');
}
